"""Regenerate the hash-locked requirement set the credential proxy installs.

The proxy sandbox holds the **real** provider key, so what runs in it should be
a fixed, verifiable set of artifacts rather than "whatever resolves today".
Pinning only the top-level `litellm[proxy]==…` leaves its transitive tree
(pydantic, aiohttp, openai, httpx, …) on ranges, which is the same drift that
broke the proxy in the first place, one level down.

This compiles ``SANDBOX_AGENT_CREDENTIAL_PROXY_REQUIREMENTS`` into
``reporting/services/sandbox_proxy_requirements.txt``: every transitive package
pinned, with hashes, installed with ``pip --require-hashes``.

    make lock_proxy_requirements

Then rebuild the template (`make build_proxy_template`) and re-probe the path
(`make remediation_smoke SMOKE_PROXY=1`).

Two resolution details matter and are easy to get wrong by hand:

- ``--no-config`` — without it ``uv`` applies *this project's* `[tool.uv]`
  constraint-dependencies to the sandbox's resolution, which is both wrong
  (they are Seizu's security floors, not the proxy's) and, today, unsolvable
  against LiteLLM's exact FastAPI pin.
- the python/platform target is the **sandbox's** (linux x86_64, see
  ``LOCK_PYTHON_VERSION``), not the version this container happens to run.
"""

import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from reporting.services import sandbox_agent  # noqa: E402

# The sandbox interpreter the lock must match — the E2B base image's, which is
# NOT this project's. Check it before changing:
#
#     docker run --rm e2bdev/base python3 --version
#
# A lock compiled for the wrong version installs fine locally and then fails in
# the sandbox with "no matching distribution", because the hashes cover wheels
# built for a different ABI. (LiteLLM 1.87.0 separately caps itself at <3.14.)
LOCK_PYTHON_VERSION = "3.11"
LOCK_PLATFORM = "x86_64-unknown-linux-gnu"


def main() -> None:
    requirements = sandbox_agent.proxy_requirements()
    if (invalid := sandbox_agent.proxy_requirements_error()) is not None:
        print(f"LOCK FAILED: {invalid}", file=sys.stderr)
        raise SystemExit(2)

    target = Path(sandbox_agent.PROXY_LOCK_PATH)
    print(f"Compiling {' '.join(requirements)} for python {LOCK_PYTHON_VERSION} ({LOCK_PLATFORM})…")
    result = subprocess.run(
        [
            "uv",
            "pip",
            "compile",
            "-",
            "--no-config",
            "--generate-hashes",
            "--no-header",
            "--no-annotate",
            "--python-version",
            LOCK_PYTHON_VERSION,
            "--python-platform",
            LOCK_PLATFORM,
        ],
        input="\n".join(requirements) + "\n",
        capture_output=True,
        text=True,
        # Resolve from a directory with no pyproject.toml, so --no-config has no
        # project settings to find even if uv's discovery changes.
        cwd="/tmp",
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        print("LOCK FAILED: uv pip compile did not resolve", file=sys.stderr)
        raise SystemExit(2)

    header = (
        f"# Generated by `make lock_proxy_requirements` — do not edit by hand.\n"
        f"# Installed into the credential-proxy sandbox with `pip --require-hashes`.\n"
        f"{sandbox_agent.PROXY_LOCK_INPUT_MARKER} {' '.join(requirements)}\n"
        f"# python: {LOCK_PYTHON_VERSION}  platform: {LOCK_PLATFORM}\n"
    )
    target.write_text(header + result.stdout)
    pins = sum(1 for line in result.stdout.splitlines() if "==" in line)
    print(f"Wrote {target} ({pins} pinned packages).")
    print("Next: `make build_proxy_template` and `make remediation_smoke SMOKE_PROXY=1`.")


if __name__ == "__main__":
    main()
